name: Static-Code-Analysis
on:
  pull_request:
permissions:
  contents: read
jobs:
  golangci-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: "--timeout 2m0s -E revive -E gosec -E gocyclo -E goimports -E errorlint -E bodyclose -E noctx"